#!/usr/bin/env bash
set -euo pipefail

AGENT="${1:-copilot}"
ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
MEMORY_DIR="$ROOT_DIR/.specify/memory"
mkdir -p "$MEMORY_DIR"

CONTEXT_FILE="$MEMORY_DIR/${AGENT}-context.md"
if [[ ! -f "$CONTEXT_FILE" ]]; then
  AGENT_TITLE="$(printf '%s' "$AGENT" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
  cat > "$CONTEXT_FILE" <<EOF
# ${AGENT_TITLE} Agent Context

Auto-generated by update-agent-context.sh.
EOF
fi

echo "Updated agent context: $CONTEXT_FILE"
